# URL de conexão: troque 'localhost:5432/psicon_db' pelo endereço e nome do seu banco criado no pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/psicon_db
spring.datasource.username=seu_usuario_do_postgres
spring.datasource.password=sua_senha_do_postgres

# Mostra no console as consultas SQL que o Java está fazendo (bom para debugar)
spring.jpa.show-sql=true
# Atualiza a estrutura do banco se você mudar as classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect