# Configuracoes do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/psicon_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracao da Porta do Servidor Web
server.port=8082